name = "Lizs Limited Liability"
author = "lizclipse"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b37a3d10ed9bf952b18f91c4f0fb8cbfac5fbd726daf1504d8b787b5ebe411a"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
