name = "Lizs Limited Liability"
author = "lizclipse"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75b7a45002751242eca196aa7ceca41b95884142297d2f67874f0a524e17cd6f"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
