name = "Lizs Limited Liability"
author = "lizclipse"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54c3d52d6b706efd5867f30d3d7823849451f8fb41de1a48e2bed7fdbcfa6772"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0-beta.8"
