name: verify & release

on:
  push:
    branches:
      - master
defaults:
  run:
    shell: nu {0}

permissions:
  contents: write

jobs:
  verify-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hustcer/setup-nu@v3.9

    - name: Pack
      id: pack
      run: |
        ./packwiz refresh
        ./packwiz modrinth export
        $"version=(open ./pack.toml | get version)(char nl)" out>> $env.GITHUB_OUTPUT
        $"mc-version=(open ./pack.toml | get versions.minecraft)(char nl)" out>> $env.GITHUB_OUTPUT

    - name: Output
      env:
        version: ${{ steps.pack.outputs.version }}
        mc_version: ${{ steps.pack.outputs.mc-version }}
      run: |
        print $"Version: ($env.version)"
        print $"Minecraft version: ($env.mc_version)"

    - uses: tj-actions/verify-changed-files@v18
      with:
        fail-if-changed: true

    - name: Autotag
      id: autotag
      env:
        version: ${{ steps.pack.outputs.version }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '88293801+lizclipse@users.noreply.github.com'
        let version = $"v($env.version)"
        let tagged = (git tag -l | lines -s | find $version | is-empty)
        if not $tagged {
          print $"pushing tag ($version)"
        }
        $"created-tag=(not $tagged)(char nl)" out>> $env.GITHUB_OUTPUT

    - name: test
      env:
        created-tag: ${{ steps.autotag.outputs.created-tag }}
      run: |
        print $"tagged: ($env.created-tag)"
