name: verify & release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hustcer/setup-nu@v3.9

    - run: |
        ./packwiz refresh

    - uses: tj-actions/verify-changed-files@v18
      with:
        fail-if-changed: true

    # - uses: butlerlogic/action-autotag@stable
    #   env:
    #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    #   with:
    #     root: ./pack.toml
    #     regex_pattern: |
    #       version = "^((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)$"
    #     tag_prefix: "v"
