name: verify & release

on:
  push:
    branches:
      - master
defaults:
  run:
    shell: nu {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hustcer/setup-nu@v3.9

    - name: pack
      id: pack
      run: |
        ./packwiz refresh
        ./packwiz modrinth export
        $"mc-version=(open ./pack.toml | get versions.minecraft)(char nl)" out>> $env.GITHUB_OUTPUT

    - name: output
      env:
        MC_VERSION: ${{ steps.pack.outputs.mc-version }}
      run: |
        print $"Minecraft version: ($env.MC_VERSION)"

    - uses: tj-actions/verify-changed-files@v18
      with:
        fail-if-changed: true

    - uses: butlerlogic/action-autotag@1.1.2
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        root: ./pack.toml
        regex_pattern: |
          version = "^((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)$"
        tag_prefix: "v"
        dry_run: true
